{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a88b2597",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2025-05-16T03:51:07.575203Z",
     "iopub.status.busy": "2025-05-16T03:51:07.574844Z",
     "iopub.status.idle": "2025-05-16T03:51:11.700092Z",
     "shell.execute_reply": "2025-05-16T03:51:11.698892Z"
    },
    "papermill": {
     "duration": 4.13114,
     "end_time": "2025-05-16T03:51:11.702265",
     "exception": false,
     "start_time": "2025-05-16T03:51:07.571125",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Year</th>\n",
       "      <th>FTAs in India (in Million)</th>\n",
       "      <th>Percentage (%) change over previous year</th>\n",
       "      <th>NRIs arrivals in India (in million)</th>\n",
       "      <th>ercentage (%) change over the previous year</th>\n",
       "      <th>International Tourist Arrivals in India  (in million)</th>\n",
       "      <th>Percentage (%) change over the previous year</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1981</td>\n",
       "      <td>1.28</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1991</td>\n",
       "      <td>1.68</td>\n",
       "      <td>-1.7</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2001</td>\n",
       "      <td>2.54</td>\n",
       "      <td>-4.2</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2002</td>\n",
       "      <td>2.38</td>\n",
       "      <td>-6.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2003</td>\n",
       "      <td>2.73</td>\n",
       "      <td>14.3</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>2004</td>\n",
       "      <td>3.46</td>\n",
       "      <td>26.8</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>2005</td>\n",
       "      <td>3.92</td>\n",
       "      <td>13.3</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>2006</td>\n",
       "      <td>4.45</td>\n",
       "      <td>13.5</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>2007</td>\n",
       "      <td>5.08</td>\n",
       "      <td>14.3</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>2008</td>\n",
       "      <td>5.28</td>\n",
       "      <td>4.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>2009</td>\n",
       "      <td>5.17</td>\n",
       "      <td>-2.2</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>2010</td>\n",
       "      <td>5.78</td>\n",
       "      <td>11.8</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>2011</td>\n",
       "      <td>6.31</td>\n",
       "      <td>9.2</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>2012</td>\n",
       "      <td>6.58</td>\n",
       "      <td>4.3</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>2013</td>\n",
       "      <td>6.97</td>\n",
       "      <td>5.9</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>2014</td>\n",
       "      <td>7.68</td>\n",
       "      <td>10.2</td>\n",
       "      <td>5.43</td>\n",
       "      <td>0.0</td>\n",
       "      <td>13.11</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>2015</td>\n",
       "      <td>8.03</td>\n",
       "      <td>4.5</td>\n",
       "      <td>5.74</td>\n",
       "      <td>5.7</td>\n",
       "      <td>13.76</td>\n",
       "      <td>5.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>2016</td>\n",
       "      <td>8.80</td>\n",
       "      <td>9.7</td>\n",
       "      <td>6.22</td>\n",
       "      <td>8.5</td>\n",
       "      <td>15.03</td>\n",
       "      <td>9.2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>2017</td>\n",
       "      <td>10.04</td>\n",
       "      <td>14.0</td>\n",
       "      <td>6.77</td>\n",
       "      <td>8.8</td>\n",
       "      <td>16.81</td>\n",
       "      <td>11.8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>2018</td>\n",
       "      <td>10.56</td>\n",
       "      <td>5.2</td>\n",
       "      <td>6.87</td>\n",
       "      <td>1.4</td>\n",
       "      <td>17.42</td>\n",
       "      <td>3.7</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>2019</td>\n",
       "      <td>10.93</td>\n",
       "      <td>3.5</td>\n",
       "      <td>6.98</td>\n",
       "      <td>1.7</td>\n",
       "      <td>17.91</td>\n",
       "      <td>2.8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>2020</td>\n",
       "      <td>2.74</td>\n",
       "      <td>-74.9</td>\n",
       "      <td>3.59</td>\n",
       "      <td>-48.6</td>\n",
       "      <td>6.33</td>\n",
       "      <td>-64.7</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    Year  FTAs in India (in Million)  \\\n",
       "0   1981                        1.28   \n",
       "1   1991                        1.68   \n",
       "2   2001                        2.54   \n",
       "3   2002                        2.38   \n",
       "4   2003                        2.73   \n",
       "5   2004                        3.46   \n",
       "6   2005                        3.92   \n",
       "7   2006                        4.45   \n",
       "8   2007                        5.08   \n",
       "9   2008                        5.28   \n",
       "10  2009                        5.17   \n",
       "11  2010                        5.78   \n",
       "12  2011                        6.31   \n",
       "13  2012                        6.58   \n",
       "14  2013                        6.97   \n",
       "15  2014                        7.68   \n",
       "16  2015                        8.03   \n",
       "17  2016                        8.80   \n",
       "18  2017                       10.04   \n",
       "19  2018                       10.56   \n",
       "20  2019                       10.93   \n",
       "21  2020                        2.74   \n",
       "\n",
       "    Percentage (%) change over previous year  \\\n",
       "0                                        2.0   \n",
       "1                                       -1.7   \n",
       "2                                       -4.2   \n",
       "3                                       -6.0   \n",
       "4                                       14.3   \n",
       "5                                       26.8   \n",
       "6                                       13.3   \n",
       "7                                       13.5   \n",
       "8                                       14.3   \n",
       "9                                        4.0   \n",
       "10                                      -2.2   \n",
       "11                                      11.8   \n",
       "12                                       9.2   \n",
       "13                                       4.3   \n",
       "14                                       5.9   \n",
       "15                                      10.2   \n",
       "16                                       4.5   \n",
       "17                                       9.7   \n",
       "18                                      14.0   \n",
       "19                                       5.2   \n",
       "20                                       3.5   \n",
       "21                                     -74.9   \n",
       "\n",
       "    NRIs arrivals in India (in million)  \\\n",
       "0                                  0.00   \n",
       "1                                  0.00   \n",
       "2                                  0.00   \n",
       "3                                  0.00   \n",
       "4                                  0.00   \n",
       "5                                  0.00   \n",
       "6                                  0.00   \n",
       "7                                  0.00   \n",
       "8                                  0.00   \n",
       "9                                  0.00   \n",
       "10                                 0.00   \n",
       "11                                 0.00   \n",
       "12                                 0.00   \n",
       "13                                 0.00   \n",
       "14                                 0.00   \n",
       "15                                 5.43   \n",
       "16                                 5.74   \n",
       "17                                 6.22   \n",
       "18                                 6.77   \n",
       "19                                 6.87   \n",
       "20                                 6.98   \n",
       "21                                 3.59   \n",
       "\n",
       "    ercentage (%) change over the previous year  \\\n",
       "0                                           0.0   \n",
       "1                                           0.0   \n",
       "2                                           0.0   \n",
       "3                                           0.0   \n",
       "4                                           0.0   \n",
       "5                                           0.0   \n",
       "6                                           0.0   \n",
       "7                                           0.0   \n",
       "8                                           0.0   \n",
       "9                                           0.0   \n",
       "10                                          0.0   \n",
       "11                                          0.0   \n",
       "12                                          0.0   \n",
       "13                                          0.0   \n",
       "14                                          0.0   \n",
       "15                                          0.0   \n",
       "16                                          5.7   \n",
       "17                                          8.5   \n",
       "18                                          8.8   \n",
       "19                                          1.4   \n",
       "20                                          1.7   \n",
       "21                                        -48.6   \n",
       "\n",
       "    International Tourist Arrivals in India  (in million)  \\\n",
       "0                                                0.00       \n",
       "1                                                0.00       \n",
       "2                                                0.00       \n",
       "3                                                0.00       \n",
       "4                                                0.00       \n",
       "5                                                0.00       \n",
       "6                                                0.00       \n",
       "7                                                0.00       \n",
       "8                                                0.00       \n",
       "9                                                0.00       \n",
       "10                                               0.00       \n",
       "11                                               0.00       \n",
       "12                                               0.00       \n",
       "13                                               0.00       \n",
       "14                                               0.00       \n",
       "15                                              13.11       \n",
       "16                                              13.76       \n",
       "17                                              15.03       \n",
       "18                                              16.81       \n",
       "19                                              17.42       \n",
       "20                                              17.91       \n",
       "21                                               6.33       \n",
       "\n",
       "    Percentage (%) change over the previous year  \n",
       "0                                            0.0  \n",
       "1                                            0.0  \n",
       "2                                            0.0  \n",
       "3                                            0.0  \n",
       "4                                            0.0  \n",
       "5                                            0.0  \n",
       "6                                            0.0  \n",
       "7                                            0.0  \n",
       "8                                            0.0  \n",
       "9                                            0.0  \n",
       "10                                           0.0  \n",
       "11                                           0.0  \n",
       "12                                           0.0  \n",
       "13                                           0.0  \n",
       "14                                           0.0  \n",
       "15                                           0.0  \n",
       "16                                           5.0  \n",
       "17                                           9.2  \n",
       "18                                          11.8  \n",
       "19                                           3.7  \n",
       "20                                           2.8  \n",
       "21                                         -64.7  "
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np \n",
    "import sklearn as sk \n",
    "import warnings\n",
    "\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "df = pd.read_csv('/kaggle/input/india-tourismdata/India-Tourism-Statistics-2021-Table-2.1.1.csv')\n",
    "\n",
    "df.drop(['Unnamed: 7','Unnamed: 8','Unnamed: 9','Unnamed: 10'],axis =1 ,  inplace = True)\n",
    "\n",
    "df.fillna(0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "ad6e5187",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2025-05-16T03:51:11.709085Z",
     "iopub.status.busy": "2025-05-16T03:51:11.708658Z",
     "iopub.status.idle": "2025-05-16T03:51:11.732070Z",
     "shell.execute_reply": "2025-05-16T03:51:11.730872Z"
    },
    "papermill": {
     "duration": 0.028689,
     "end_time": "2025-05-16T03:51:11.733838",
     "exception": false,
     "start_time": "2025-05-16T03:51:11.705149",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Months</th>\n",
       "      <th>2019</th>\n",
       "      <th>2020</th>\n",
       "      <th>2021</th>\n",
       "      <th>Growth 2020/19 (%)</th>\n",
       "      <th>Growth 2021/20 (%)</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>January</td>\n",
       "      <td>440907</td>\n",
       "      <td>611702</td>\n",
       "      <td>486338</td>\n",
       "      <td>38.74</td>\n",
       "      <td>-20.49</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>February</td>\n",
       "      <td>402203</td>\n",
       "      <td>495109</td>\n",
       "      <td>431118</td>\n",
       "      <td>23.10</td>\n",
       "      <td>-12.92</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>March</td>\n",
       "      <td>484602</td>\n",
       "      <td>287681</td>\n",
       "      <td>479317</td>\n",
       "      <td>-40.64</td>\n",
       "      <td>66.61</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>April</td>\n",
       "      <td>507704</td>\n",
       "      <td>233</td>\n",
       "      <td>413089</td>\n",
       "      <td>-99.95</td>\n",
       "      <td>177191.42</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>May</td>\n",
       "      <td>618600</td>\n",
       "      <td>25760</td>\n",
       "      <td>204898</td>\n",
       "      <td>-95.84</td>\n",
       "      <td>695.41</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "     Months    2019    2020    2021  Growth 2020/19 (%)  Growth 2021/20 (%)\n",
       "0   January  440907  611702  486338               38.74              -20.49\n",
       "1  February  402203  495109  431118               23.10              -12.92\n",
       "2     March  484602  287681  479317              -40.64               66.61\n",
       "3     April  507704     233  413089              -99.95           177191.42\n",
       "4       May  618600   25760  204898              -95.84              695.41"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df1 = pd.read_csv('/kaggle/input/monthwisetourism/India-Tourism-Statistics-2022-TABLE-2.1.2.csv')\n",
    "\n",
    "df1.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "503c6125",
   "metadata": {
    "papermill": {
     "duration": 0.002145,
     "end_time": "2025-05-16T03:51:11.738581",
     "exception": false,
     "start_time": "2025-05-16T03:51:11.736436",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6595de5f",
   "metadata": {
    "papermill": {
     "duration": 0.001958,
     "end_time": "2025-05-16T03:51:11.742873",
     "exception": false,
     "start_time": "2025-05-16T03:51:11.740915",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1489fcfc",
   "metadata": {
    "papermill": {
     "duration": 0.001897,
     "end_time": "2025-05-16T03:51:11.747030",
     "exception": false,
     "start_time": "2025-05-16T03:51:11.745133",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kaggle": {
   "accelerator": "none",
   "dataSources": [
    {
     "datasetId": 7427450,
     "sourceId": 11823922,
     "sourceType": "datasetVersion"
    },
    {
     "datasetId": 7427581,
     "sourceId": 11824093,
     "sourceType": "datasetVersion"
    }
   ],
   "dockerImageVersionId": 31040,
   "isGpuEnabled": false,
   "isInternetEnabled": true,
   "language": "python",
   "sourceType": "notebook"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.11"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 10.220531,
   "end_time": "2025-05-16T03:51:12.471206",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2025-05-16T03:51:02.250675",
   "version": "2.6.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
